server:
  port: 8087

spring:
  application:
    name: inventory-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # IMPORTANT (Liquibase manages schema)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC


waiting-room:
  enabled: true
  default-capacity: 100
  admission-pass-ttl: 2m
  waiting-token-ttl: 1h
  admission-interval-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
